# Generated by Django 6.0.3 on 2026-04-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=5, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('etat_civil', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)')], max_length=12, verbose_name='État civil')),
                ('telephone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Téléphone')),
                ('fonction', models.CharField(choices=[('Directeur', 'Directeur'), ('Manager', 'Manager'), ('Employé', 'Employé'), ('Stagiaire', 'Stagiaire'), ('Autre', 'Autre')], max_length=50, verbose_name='Fonction')),
            ],
        ),
    ]
